// =========================================================================
// WORKCRAFT TARGET FILE CONFIGURATION MAPPING (TOP-LEVEL POST-SYNTHESIS)
// =========================================================================

// Point directly to the post-synthesis netlist generated by the GDS run
var designFile = "../gds_drop/runs/wokcraft_run/results/synthesis/tt_um_c061618g2.v";
var circuitModel = framework.load(designFile);

if (circuitModel == null) {
    framework.printError("Failed to parse the top-level structural gate netlist.");
    framework.exit(1);
}

// Target the full chip loop and hazard properties
framework.printStatus("Scanning top-level and submodules for asynchronous deadlocks...");
var deadlockClean = circuit.checkDeadlock(circuitModel);

framework.printStatus("Scanning full combinational matrix for hazard propagation...");
var hazardsClean = circuit.checkHazards(circuitModel);

if (!deadlockClean || !hazardsClean) {
    framework.printError("FAIL: Clockless boundary or submodule loop hazard detected.");
    framework.exit(1);
} else {
    framework.printStatus("PASS: All top-level paths and async submodules are fully verified!");
    framework.exit(0);
}
