// =========================================================================
// WORKCRAFT TARGET FILE CONFIGURATION MAPPING (TOP-LEVEL POST-SYNTHESIS)
// =========================================================================

// Point directly to the post-synthesis netlist generated by the GDS run
var designFile = "../gds_drop/runs/wokcraft_run/results/synthesis/tt_um_c061618g2.v";
var circuitModel = load(designFile);

if (circuitModel == null) {
    print("ERROR: Failed to parse the top-level structural gate netlist.");
    exit();
}

// FIX: Grab the underlying Verification Tools JavaScript plugin wrapper
var circuitTools = framework.getPluginManager().getCommand("org.workcraft.plugins.circuit.commands.CheckDeadlockCommand");

if (circuitTools == null) {
    print("ERROR: Digital Circuit tool suite is not loaded in this environment.");
    exit();
}

// Target the full chip loop and hazard properties
print("Scanning top-level and submodules for asynchronous deadlocks...");
// Execute verification natively through the framework context
var deadlockClean = framework.executeCommand(circuitModel, "org.workcraft.plugins.circuit.commands.CheckDeadlockCommand");

print("Scanning full combinational matrix for hazard propagation...");
var hazardsClean = framework.executeCommand(circuitModel, "org.workcraft.plugins.circuit.commands.CheckHazardsCommand");

if (!deadlockClean || !hazardsClean) {
    print("FAIL: Clockless boundary or submodule loop hazard detected.");
    exit();
} else {
    print("PASS: All top-level paths and async submodules are fully verified!");
    exit();
}
